server: &server
  adapter: postgresql
  encoding: unicode
  reconnect: false
  pool: 5
  host: 127.0.0.1
  port: 5432

development:
  adapter: postgresql
  database: db/spree_demo_store_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: db/spree_demo_store_test
  pool: 5
  timeout: 5000

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
